name: lighthouse-ci

on: 
  push:
    paths:
      - "**/**.svelte"
      - "**/**.ts"
    
jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install && npm install -g @lhci/cli@0.13.x

      - run: npm run build

      - run: lhci autorun --collect.settings.preset=desktop
        continue-on-error: true
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - run: lhci autorun
        continue-on-error: true
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
